### ISSUE TITLE
UE 5.0 Grip Tracking Issue

### ISSUE THREAD

**Issue by 2point1creations** [mordentral/VRExpansionPlugin#17]
I've noticed 2 issues with the 5.0 pre-release and the 5.0 template.    Both seem to be related to tracking. 

1.  If you grab the example gun with a single hand and hold it very still for a few seconds. The hand that is gripped stays in place however if you move the motion control, the gun moves as intended.  This causes the hand to stay in place and jitter.  The only way to fix it is to release the grab and restart. 
2. The hand movement when gripping any object (basic cube or gun) becomes really slow compared to when you are not gripping anything.   Essentially if you wave your hand in vr with nothing in it, then pick up the cube and wave your hand you will notice that your wave with the cube gripped is about half the speed of your real life hands movements.  

I am using the Vive Character provided in the UE5 template.  I have updated the plugins with the last commits from a few days ago.  

I've made a little video to better demonstrate. 

https://youtu.be/X_zLry7ZeMo

Throughout the video anytime i have grabbed an object, I am holding the grab button on the oculus controller until it is released and everything from a grab perspective seems to reset.  

Its important to note that this project hasn't been modified in any way except that I added on blueprint for a gun test. The code for the pawn, cubes and example guns have not been modified in any way.  

Thanks again in advance this plugin simply rocks on 4.27!  So excited to see it polished in 5.

Side Note: The above 2 issues do NOT occur in the 4.27 build so i believe it has something to do with UE5 specifically.

**Comment by mordentral** [comment]
It is something to do with Chaos specifically, its an engine bug with the new physics engine where it won't wake objects out of sleep until another simulating object is brought within a range of them. The UE5 EA build is on a fairly old (and buggy) version of chaos.

4.27-chaos branch is newer (though still has the same bug present). Its been fixed internally I hear and may be working on the current master branch of ue5.

As for the slow movement after grip, chaos uses much different physics settings than physx, there are automatic adjustment variables but they need tweaked further for the damping value which behaves very unlike physx's ones. I haven't bothered to go in and tweak every objects settings since Chaos IS broken and I can't trust that I won't have to do it again later since they had stated they wanted physx parity.

**Comment by mordentral** [comment]
You should be able to use non physics based grips fairly freely in UE5 EA, but like stated, physical ones are going to have issues in that current engine build. I'll also note that VR in UE5 is pretty much pointless at the moment (another reason I haven't focused on it much yet), none of the new rendering features work in VR yet so its still ue4 rendering and Chaos in current builds is a straight downgrade from physx.

**Comment by 2point1creations** [comment]
Thank you for the detailed explanation.  I really appreciate it and your development approach makes perfect sense given the amount of unknowns with  Early Access of 5.  I will close out this comment.
