### ISSUE TITLE
Not an issue with the plugin, but perhaps my skill issue

### ISSUE THREAD

**Issue by moseechev** [mordentral/VRExpansionPlugin#23]
So I've been trying to implement a pistol in the game. I'm using your example location.
Now, I've decided to stick for tutorials for now, since I'm a complete noob in UE development. A tutorial said, "if you're noob, it's better that you learn from guides or something ready, so we're going to stick for that plan for now. for example, to implement a gun, it's not necessarily to be a UE god, you can just copy a GunBase from the example, edit the mesh, maybe implement something you CAN do such as bolt action, magazine reload and keep enjoying the life". Well, I tried doing that...
So first, I've copied the GunBase actor into another folder:
https://imgur.com/a/jVtWWqn

Then, I've tried replacing the mesh. Uh, it turned out that it was too big so I had to resize it by 0.01 in all directions. (maybe this is the reason why this doesn't work, but I'm too tired to recompile the entire model)
Now, I know the hands aren't positioned correctly, but trust me when I say I've been positioning them correctly like 5 or 6 times, but this didn't work and I had to delete it and try again.
https://imgur.com/a/9oUtPGI

I can't attach a video because it would have AWFUL quality, so let me explain how it works in VR.
Your hand IS gripped, but it's not gripped to the socket. It works not how a GunBase gripping works, but how a lemon juice bottle gripping works. I hope you get it.

Now, with all of that, I also have some other questions.
How to change the ungripping? I don't want to ungrip by releasing the controller's grip, and I don't want to ungrip by pressing the controller's lowest button in case with guns either. I want to make it so that you ungrip when you press the controller's grip for the second time. In other words, toggling.

Thank you in advance.

**Comment by mordentral** [comment]
Set both of the HandSocketComponents in your new actor to bAlwaysInRange in their properties. The socket range finding is in the actors space (so if you scale an object heavily it will still find sockets relative to the same locations on it). However since your gun is 100x the size it should be and you are just scaling it down, the socket ranges are far too short to be found from most grip searching locations. For a pistol you don't need free gripping anyway though and bAlwaysInRange will have the sockets always be used.

As for the input toggling, the template gunbase changes some gameplay tags on it based on where it was gripped at. You can either remove that logic and directly add the input tags that you want to it, or edit them to change it from SecondaryGrip.Pressed to drop to PrimaryGrip.Pressed and it will do what you want.

You also should join the plugins discord, its a lot easier to answer things in there (direct linking) and members of the community are willing to help out if I am unavailable.
